feat!: decoupled builder (#756)
* feat: decouple image builder from worker

Signed-off-by: SdgJlbl <sarah.diot-girard@owkin.com>

* fix: update skaffold config

Signed-off-by: Guilhem Barthes <guilhem.barthes@owkin.com>

* feat: add `ServiceAccount` and modify role

Signed-off-by: Guilhem Barthes <guilhem.barthes@owkin.com>

* fix: improve `wait_for_image_built`

Signed-off-by: Guilhem Barthes <guilhem.barthes@owkin.com>

* feat: build image in new pod

Signed-off-by: Guilhem Barthes <guilhem.barthes@owkin.com>

* chore: rename `deployment-builder.yaml` to `stateful-builder.yaml`

Signed-off-by: Guilhem Barthes <guilhem.barthes@owkin.com>

* chore: rename `stateful-builder.yaml` to `statefulset-builder.yaml`

Signed-off-by: Guilhem Barthes <guilhem.barthes@owkin.com>

* chore: centralize params

Signed-off-by: Guilhem Barthes <guilhem.barthes@owkin.com>

* feat: create `BuildTask`

Signed-off-by: Guilhem Barthes <guilhem.barthes@owkin.com>

* feat: move some values to `builder` module

Signed-off-by: Guilhem Barthes <guilhem.barthes@owkin.com>

* feat: move more code to `builder`

Signed-off-by: Guilhem Barthes <guilhem.barthes@owkin.com>

* fix: remove TaskProfiling as Celery task + save Entrypoint in DB

Signed-off-by: SdgJlbl <sarah.diot-girard@owkin.com>

* fix: extract entrypoint from registry

Signed-off-by: SdgJlbl <sarah.diot-girard@owkin.com>

* fix: make doc for helm chart

Signed-off-by: SdgJlbl <sarah.diot-girard@owkin.com>

* feat: build function at registration (#707)

<!-- Please reference issue if any. -->

<!-- Please include a summary of your changes. -->

<!-- Please describe the tests that you ran to verify your changes.  -->

- [ ] [changelog](../CHANGELOG.md) was updated with notable changes
- [ ] documentation was updated

---------

Signed-off-by: SdgJlbl <sarah.diot-girard@owkin.com>
Signed-off-by: Guilhem Barthes <guilhem.barthes@owkin.com>
Co-authored-by: SdgJlbl <sarah.diot-girard@owkin.com>

* feat: share images between backends (#708)



Signed-off-by: SdgJlbl <sarah.diot-girard@owkin.com>

* chore: update helm worklfow

Signed-off-by: ThibaultFy <50656860+ThibaultFy@users.noreply.github.com>

* chore: add .DS_Store to gitignore

Signed-off-by: ThibaultFy <50656860+ThibaultFy@users.noreply.github.com>

* chore: rm DS_Store

Signed-off-by: ThibaultFy <50656860+ThibaultFy@users.noreply.github.com>

* chore: rm .DS_Store

Signed-off-by: ThibaultFy <50656860+ThibaultFy@users.noreply.github.com>

* [sub]fix: add missing migration poc (#728)

## Description

Add a migration missing in the poc. 
This migration alters two things:

-  modify `ComputeTaskFailureReport.logs` 
-  modify `FunctionImage.file`

This migration has been generated automatically with `make migrations`

## How has this been tested?

<!-- Please describe the tests that you ran to verify your changes.  -->

## Checklist

- [ ] [changelog](../CHANGELOG.md) was updated with notable changes
- [ ] documentation was updated

Signed-off-by: Guilhem Barthes <guilhem.barthes@owkin.com>

* [sub]feat: add function events (#714)

- https://github.com/Substra/orchestrator/pull/263

Add function events, used now we decoupled the building of the function
with the execution of the compute task. For that it add a status field
on the Function. It also includes another PR (merged here), to have
functions build logs working again.

In a future PR, we will change the compute task execution to avoid
having to wait_for_function_built in compute_task()

Fixes FL-1160

As this is going to be merged on a branch that is going to be merged to
a POC branch, we use MNIST as a baseline of a working model. We will
deal with failing tests on the POC before merging on main.

- [x] [changelog](../CHANGELOG.md) was updated with notable changes
- [ ] documentation was updated

---------

Signed-off-by: SdgJlbl <sarah.diot-girard@owkin.com>
Signed-off-by: Guilhem Barthes <guilhem.barthes@owkin.com>
Signed-off-by: Guilhem Barthés <guilhem.barthes@owkin.com>
Co-authored-by: SdgJlbl <sarah.diot-girard@owkin.com>

* [sub]fix(app/orchestrator/resources): FunctionStatus.FUNCTION_STATUS_CREATED -> FunctionStatus.FUNCTION_STATUS_WAITING (#742)

# Issue

Backend FunctionStatus are not aligned with [orchestrator
definitions](https://github.com/Substra/orchestrator/blob/poc-decoupled-builder/lib/asset/function.proto#L29-L36).
In particular, `FunctionStatus.FUNCTION_STATUS_CREATED` leading to the
following error:

```txt
ValueError: 'FUNCTION_STATUS_WAITING' is not a valid FunctionStatus
```

## Description

FunctionStatus.FUNCTION_STATUS_CREATED ->
FunctionStatus.FUNCTION_STATUS_WAITING

## How has this been tested?

Running Camelyon benchmark on
[poc-builder-flpc](https://substra.org-1.poc-builder-flpc.cg.owkin.tech/compute_plans/a420306f-5719-412b-ab9c-688b7bed9c70/tasks?page=1&ordering=-rank)
environment.

## Checklist

- [ ] [changelog](../CHANGELOG.md) was updated with notable changes
- [ ] documentation was updated

---------

Signed-off-by: Thibault Camalon <135698225+thbcmlowk@users.noreply.github.com>

* fix: builder using builder SA (#754)

* fix: builder using builder SA

Signed-off-by: Guilhem Barthés <guilhem.barthes@owkin.com>

* docs: changelog

Signed-off-by: Guilhem Barthés <guilhem.barthes@owkin.com>

---------

Signed-off-by: Guilhem Barthés <guilhem.barthes@owkin.com>

* fix: rebase changelog

Signed-off-by: Guilhem Barthés <guilhem.barthes@owkin.com>

* fix: adapt to pydantic 2.x.x (#758)

Signed-off-by: Guilhem Barthés <guilhem.barthes@owkin.com>

* [sub]fix(backend/image_transfert/encoder): update pydantic method (#763)

* fix(backend/image_transfert/encoder): update pydantic method

Signed-off-by: Thibault Camalon <135698225+thbcmlowk@users.noreply.github.com>

* fix(backend/image_transfer/decoder): parse_raw -> model_validate_json

Signed-off-by: Thibault Camalon <135698225+thbcmlowk@users.noreply.github.com>

---------

Signed-off-by: Thibault Camalon <135698225+thbcmlowk@users.noreply.github.com>

* [sub]chore: upgrade chart (#765)

* chore(charts): bump chart version

Signed-off-by: Thibault Camalon <135698225+thbcmlowk@users.noreply.github.com>

* chore(charts/substra-backend/CHANGELOG): bring back unreleased section

Signed-off-by: Thibault Camalon <135698225+thbcmlowk@users.noreply.github.com>

---------

Signed-off-by: Thibault Camalon <135698225+thbcmlowk@users.noreply.github.com>

* fix: post-rebase

Signed-off-by: SdgJlbl <sarah.diot-girard@owkin.com>

* chore: rationalize migrations

Signed-off-by: SdgJlbl <sarah.diot-girard@owkin.com>

* [sub]chore(builder): waitPostgresqlInitContainer (#764)

* fix: builder using builder SA (#754)

* fix: builder using builder SA

Signed-off-by: Guilhem Barthés <guilhem.barthes@owkin.com>

* docs: changelog

Signed-off-by: Guilhem Barthés <guilhem.barthes@owkin.com>

---------

Signed-off-by: Guilhem Barthés <guilhem.barthes@owkin.com>

* chore(charts/substra-backend/templates/statefulset-builder): add init-container waitPostgresqlInitContainer

Signed-off-by: Thibault Camalon <135698225+thbcmlowk@users.noreply.github.com>

---------

Signed-off-by: Guilhem Barthés <guilhem.barthes@owkin.com>
Signed-off-by: Thibault Camalon <135698225+thbcmlowk@users.noreply.github.com>
Co-authored-by: Guilhem Barthés <guilhem.barthes@owkin.com>

---------

Signed-off-by: SdgJlbl <sarah.diot-girard@owkin.com>
Signed-off-by: Guilhem Barthes <guilhem.barthes@owkin.com>
Signed-off-by: ThibaultFy <50656860+ThibaultFy@users.noreply.github.com>
Signed-off-by: Guilhem Barthés <guilhem.barthes@owkin.com>
Signed-off-by: Thibault Camalon <135698225+thbcmlowk@users.noreply.github.com>
Co-authored-by: SdgJlbl <sarah.diot-girard@owkin.com>
Co-authored-by: ThibaultFy <50656860+ThibaultFy@users.noreply.github.com>
Co-authored-by: Thibault Camalon <135698225+thbcmlowk@users.noreply.github.com>